load("@com_google_j2cl//build_defs:rules.bzl", "j2cl_library")

package(
    default_visibility = ["//visibility:public"],
)

j2cl_library(
    name = "java_io",
    srcs = [
        "BufferedReader.java",
        "InputStreamReader.java",
    ],
)

j2cl_library(
    name = "java_net",
    srcs = [
        "URI.java",
        "URISyntaxException.java",
    ],
)

j2cl_library(
    name = "java_nio_file",
    srcs = [
        "InvalidPathException.java",
        "Path.java",
        "Paths.java",
    ],
)
