package org.dhallj.tests.acceptance

class HashingBoolAndSuite extends HashingSuite("semantic-hash/success/prelude/Bool/and")
class HashingBoolBuildSuite extends HashingSuite("semantic-hash/success/prelude/Bool/build")
class HashingBoolEvenSuite extends HashingSuite("semantic-hash/success/prelude/Bool/even")
class HashingBoolFoldSuite extends HashingSuite("semantic-hash/success/prelude/Bool/fold")
class HashingBoolNotSuite extends HashingSuite("semantic-hash/success/prelude/Bool/not")
class HashingBoolOddSuite extends HashingSuite("semantic-hash/success/prelude/Bool/odd")
class HashingBoolOrSuite extends HashingSuite("semantic-hash/success/prelude/Bool/or")
class HashingBoolShowSuite extends HashingSuite("semantic-hash/success/prelude/Bool/show")

class HashingDoubleShowSuite extends HashingSuite("semantic-hash/success/prelude/Double/show")
class HashingIntegerShowSuite extends HashingSuite("semantic-hash/success/prelude/Integer/show")
class HashingIntegerToDoubleSuite extends HashingSuite("semantic-hash/success/prelude/Integer/toDouble")

class HashingListAllSuite extends HashingSuite("semantic-hash/success/prelude/List/all")
class HashingListBuildSuite extends HashingSuite("semantic-hash/success/prelude/List/build")
class HashingListConcatMapSuite extends HashingSuite("semantic-hash/success/prelude/List/concatMap")
class HashingListFoldSuite extends HashingSuite("semantic-hash/success/prelude/List/fold")
class HashingListHeadSuite extends HashingSuite("semantic-hash/success/prelude/List/head")
class HashingListIterateSuite extends HashingSuite("semantic-hash/success/prelude/List/iterate")
class HashingListLengthSuite extends HashingSuite("semantic-hash/success/prelude/List/length")
class HashingListNullSuite extends HashingSuite("semantic-hash/success/prelude/List/null")
class HashingListReverseSuite extends HashingSuite("semantic-hash/success/prelude/List/reverse")
class HashingListUnzipSuite extends HashingSuite("semantic-hash/success/prelude/List/unzip")
class HashingListAnySuite extends HashingSuite("semantic-hash/success/prelude/List/any")
class HashingListConcatSuite extends HashingSuite("semantic-hash/success/prelude/List/concat")
class HashingListFilterSuite extends HashingSuite("semantic-hash/success/prelude/List/filter")
class HashingListGenerateSuite extends HashingSuite("semantic-hash/success/prelude/List/generate")
class HashingListIndexedSuite extends HashingSuite("semantic-hash/success/prelude/List/indexed")
class HashingListLastSuite extends HashingSuite("semantic-hash/success/prelude/List/last")
class HashingListMapSuite extends HashingSuite("semantic-hash/success/prelude/List/map")
class HashingListReplicateSuite extends HashingSuite("semantic-hash/success/prelude/List/replicate")
class HashingListShiftedSuite extends HashingSuite("semantic-hash/success/prelude/List/shifted")

class HashingNaturalBuildSuite extends HashingSuite("semantic-hash/success/prelude/Natural/build")
class HashingNaturalEnumerateSuite extends HashingSuite("semantic-hash/success/prelude/Natural/enumerate")
class HashingNaturalEvenSuite extends HashingSuite("semantic-hash/success/prelude/Natural/even")
class HashingNaturalFoldSuite extends HashingSuite("semantic-hash/success/prelude/Natural/fold")
class HashingNaturalIsZeroSuite extends HashingSuite("semantic-hash/success/prelude/Natural/isZero")
class HashingNaturalOddSuite extends HashingSuite("semantic-hash/success/prelude/Natural/odd")
class HashingNaturalProductSuite extends HashingSuite("semantic-hash/success/prelude/Natural/product")
class HashingNaturalShowSuite extends HashingSuite("semantic-hash/success/prelude/Natural/show")
class HashingNaturalSumSuite extends HashingSuite("semantic-hash/success/prelude/Natural/sum")
class HashingNaturalToDoubleSuite extends HashingSuite("semantic-hash/success/prelude/Natural/toDouble")
class HashingNaturalToIntegerSuite extends HashingSuite("semantic-hash/success/prelude/Natural/toInteger")

class HashingOptionalAllSuite extends HashingSuite("semantic-hash/success/prelude/Optional/all")
class HashingOptionalAnySuite extends HashingSuite("semantic-hash/success/prelude/Optional/any")
class HashingOptionalBuildSuite extends HashingSuite("semantic-hash/success/prelude/Optional/build")
class HashingOptionalConcatSuite extends HashingSuite("semantic-hash/success/prelude/Optional/concat")
class HashingOptionalFilterSuite extends HashingSuite("semantic-hash/success/prelude/Optional/filter")
class HashingOptionalFoldSuite extends HashingSuite("semantic-hash/success/prelude/Optional/fold")
class HashingOptionalHeadSuite extends HashingSuite("semantic-hash/success/prelude/Optional/head")
class HashingOptionalLastSuite extends HashingSuite("semantic-hash/success/prelude/Optional/last")
class HashingOptionalLengthSuite extends HashingSuite("semantic-hash/success/prelude/Optional/length")
class HashingOptionalMapSuite extends HashingSuite("semantic-hash/success/prelude/Optional/map")
class HashingOptionalNullSuite extends HashingSuite("semantic-hash/success/prelude/Optional/null")
class HashingOptionalToListSuite extends HashingSuite("semantic-hash/success/prelude/Optional/toList")
class HashingOptionalUnzipSuite extends HashingSuite("semantic-hash/success/prelude/Optional/unzip")

class HashingTextConcatSuite extends HashingSuite("semantic-hash/success/prelude/Text/concat")
class HashingTextConcatMapSuite extends HashingSuite("semantic-hash/success/prelude/Text/concatMap")
class HashingTextConcatMapSepSuite extends HashingSuite("semantic-hash/success/prelude/Text/concatMapSep")
class HashingTextConcatSepSuite extends HashingSuite("semantic-hash/success/prelude/Text/concatSep")
class HashingTextShowSuite extends HashingSuite("semantic-hash/success/prelude/Text/show")
