package org.dhallj.tests.acceptance

class HashingPreludeBoolAndSuite extends PreludeHashingSuite("semantic-hash/success/prelude/Bool/and")
class HashingPreludeBoolBuildSuite extends PreludeHashingSuite("semantic-hash/success/prelude/Bool/build")
class HashingPreludeBoolEvenSuite extends PreludeHashingSuite("semantic-hash/success/prelude/Bool/even")
class HashingPreludeBoolFoldSuite extends PreludeHashingSuite("semantic-hash/success/prelude/Bool/fold")
class HashingPreludeBoolNotSuite extends PreludeHashingSuite("semantic-hash/success/prelude/Bool/not")
class HashingPreludeBoolOddSuite extends PreludeHashingSuite("semantic-hash/success/prelude/Bool/odd")
class HashingPreludeBoolOrSuite extends PreludeHashingSuite("semantic-hash/success/prelude/Bool/or")
class HashingPreludeBoolShowSuite extends PreludeHashingSuite("semantic-hash/success/prelude/Bool/show")

class HashingPreludeDoubleShowSuite extends PreludeHashingSuite("semantic-hash/success/prelude/Double/show")
class HashingPreludeIntegerShowSuite extends PreludeHashingSuite("semantic-hash/success/prelude/Integer/show")
class HashingPreludeIntegerToDoubleSuite extends PreludeHashingSuite("semantic-hash/success/prelude/Integer/toDouble")

class HashingPreludeListAllSuite extends PreludeHashingSuite("semantic-hash/success/prelude/List/all")
class HashingPreludeListBuildSuite extends PreludeHashingSuite("semantic-hash/success/prelude/List/build")
class HashingPreludeListConcatMapSuite extends PreludeHashingSuite("semantic-hash/success/prelude/List/concatMap")
class HashingPreludeListFoldSuite extends PreludeHashingSuite("semantic-hash/success/prelude/List/fold")
class HashingPreludeListHeadSuite extends PreludeHashingSuite("semantic-hash/success/prelude/List/head")
class HashingPreludeListIterateSuite extends PreludeHashingSuite("semantic-hash/success/prelude/List/iterate")
class HashingPreludeListLengthSuite extends PreludeHashingSuite("semantic-hash/success/prelude/List/length")
class HashingPreludeListNullSuite extends PreludeHashingSuite("semantic-hash/success/prelude/List/null")
class HashingPreludeListReverseSuite extends PreludeHashingSuite("semantic-hash/success/prelude/List/reverse")
class HashingPreludeListUnzipSuite extends PreludeHashingSuite("semantic-hash/success/prelude/List/unzip")
class HashingPreludeListAnySuite extends PreludeHashingSuite("semantic-hash/success/prelude/List/any")
class HashingPreludeListConcatSuite extends PreludeHashingSuite("semantic-hash/success/prelude/List/concat")
class HashingPreludeListFilterSuite extends PreludeHashingSuite("semantic-hash/success/prelude/List/filter")
class HashingPreludeListGenerateSuite extends PreludeHashingSuite("semantic-hash/success/prelude/List/generate")
class HashingPreludeListIndexedSuite extends PreludeHashingSuite("semantic-hash/success/prelude/List/indexed")
class HashingPreludeListLastSuite extends PreludeHashingSuite("semantic-hash/success/prelude/List/last")
class HashingPreludeListMapSuite extends PreludeHashingSuite("semantic-hash/success/prelude/List/map")
class HashingPreludeListReplicateSuite extends PreludeHashingSuite("semantic-hash/success/prelude/List/replicate")
class HashingPreludeListShiftedSuite extends PreludeHashingSuite("semantic-hash/success/prelude/List/shifted")

class HashingPreludeNaturalBuildSuite extends PreludeHashingSuite("semantic-hash/success/prelude/Natural/build")
class HashingPreludeNaturalEnumerateSuite extends PreludeHashingSuite("semantic-hash/success/prelude/Natural/enumerate")
class HashingPreludeNaturalEvenSuite extends PreludeHashingSuite("semantic-hash/success/prelude/Natural/even")
class HashingPreludeNaturalFoldSuite extends PreludeHashingSuite("semantic-hash/success/prelude/Natural/fold")
class HashingPreludeNaturalIsZeroSuite extends PreludeHashingSuite("semantic-hash/success/prelude/Natural/isZero")
class HashingPreludeNaturalOddSuite extends PreludeHashingSuite("semantic-hash/success/prelude/Natural/odd")
class HashingPreludeNaturalProductSuite extends PreludeHashingSuite("semantic-hash/success/prelude/Natural/product")
class HashingPreludeNaturalShowSuite extends PreludeHashingSuite("semantic-hash/success/prelude/Natural/show")
class HashingPreludeNaturalSumSuite extends PreludeHashingSuite("semantic-hash/success/prelude/Natural/sum")
class HashingPreludeNaturalToDoubleSuite extends PreludeHashingSuite("semantic-hash/success/prelude/Natural/toDouble")
class HashingPreludeNaturalToIntegerSuite extends PreludeHashingSuite("semantic-hash/success/prelude/Natural/toInteger")

class HashingPreludeOptionalAllSuite extends PreludeHashingSuite("semantic-hash/success/prelude/Optional/all")
class HashingPreludeOptionalAnySuite extends PreludeHashingSuite("semantic-hash/success/prelude/Optional/any")
class HashingPreludeOptionalBuildSuite extends PreludeHashingSuite("semantic-hash/success/prelude/Optional/build")
class HashingPreludeOptionalConcatSuite extends PreludeHashingSuite("semantic-hash/success/prelude/Optional/concat")
class HashingPreludeOptionalFilterSuite extends PreludeHashingSuite("semantic-hash/success/prelude/Optional/filter")
class HashingPreludeOptionalFoldSuite extends PreludeHashingSuite("semantic-hash/success/prelude/Optional/fold")
class HashingPreludeOptionalHeadSuite extends PreludeHashingSuite("semantic-hash/success/prelude/Optional/head")
class HashingPreludeOptionalLastSuite extends PreludeHashingSuite("semantic-hash/success/prelude/Optional/last")
class HashingPreludeOptionalLengthSuite extends PreludeHashingSuite("semantic-hash/success/prelude/Optional/length")
class HashingPreludeOptionalMapSuite extends PreludeHashingSuite("semantic-hash/success/prelude/Optional/map")
class HashingPreludeOptionalNullSuite extends PreludeHashingSuite("semantic-hash/success/prelude/Optional/null")
class HashingPreludeOptionalToListSuite extends PreludeHashingSuite("semantic-hash/success/prelude/Optional/toList")
class HashingPreludeOptionalUnzipSuite extends PreludeHashingSuite("semantic-hash/success/prelude/Optional/unzip")

class HashingPreludeTextConcatSuite extends PreludeHashingSuite("semantic-hash/success/prelude/Text/concat")
class HashingPreludeTextConcatMapSuite extends PreludeHashingSuite("semantic-hash/success/prelude/Text/concatMap")
class HashingPreludeTextConcatMapSepSuite extends PreludeHashingSuite("semantic-hash/success/prelude/Text/concatMapSep")
class HashingPreludeTextConcatSepSuite extends PreludeHashingSuite("semantic-hash/success/prelude/Text/concatSep")
class HashingPreludeTextShowSuite extends PreludeHashingSuite("semantic-hash/success/prelude/Text/show")
