package org.dhallj.tests.acceptance

class HashingPreludeBoolAndSuite extends HashingSuite("semantic-hash/success/prelude/Bool/and")
class HashingPreludeBoolBuildSuite extends HashingSuite("semantic-hash/success/prelude/Bool/build")
class HashingPreludeBoolEvenSuite extends HashingSuite("semantic-hash/success/prelude/Bool/even")
class HashingPreludeBoolFoldSuite extends HashingSuite("semantic-hash/success/prelude/Bool/fold")
class HashingPreludeBoolNotSuite extends HashingSuite("semantic-hash/success/prelude/Bool/not")
class HashingPreludeBoolOddSuite extends HashingSuite("semantic-hash/success/prelude/Bool/odd")
class HashingPreludeBoolOrSuite extends HashingSuite("semantic-hash/success/prelude/Bool/or")
class HashingPreludeBoolShowSuite extends HashingSuite("semantic-hash/success/prelude/Bool/show")

class HashingPreludeDoubleShowSuite extends HashingSuite("semantic-hash/success/prelude/Double/show")
class HashingPreludeIntegerShowSuite extends HashingSuite("semantic-hash/success/prelude/Integer/show")
class HashingPreludeIntegerToDoubleSuite extends HashingSuite("semantic-hash/success/prelude/Integer/toDouble")

class HashingPreludeListAllSuite extends HashingSuite("semantic-hash/success/prelude/List/all")
class HashingPreludeListBuildSuite extends HashingSuite("semantic-hash/success/prelude/List/build")
class HashingPreludeListConcatMapSuite extends HashingSuite("semantic-hash/success/prelude/List/concatMap")
class HashingPreludeListFoldSuite extends HashingSuite("semantic-hash/success/prelude/List/fold")
class HashingPreludeListHeadSuite extends HashingSuite("semantic-hash/success/prelude/List/head")
class HashingPreludeListIterateSuite extends HashingSuite("semantic-hash/success/prelude/List/iterate")
class HashingPreludeListLengthSuite extends HashingSuite("semantic-hash/success/prelude/List/length")
class HashingPreludeListNullSuite extends HashingSuite("semantic-hash/success/prelude/List/null")
class HashingPreludeListReverseSuite extends HashingSuite("semantic-hash/success/prelude/List/reverse")
class HashingPreludeListUnzipSuite extends HashingSuite("semantic-hash/success/prelude/List/unzip")
class HashingPreludeListAnySuite extends HashingSuite("semantic-hash/success/prelude/List/any")
class HashingPreludeListConcatSuite extends HashingSuite("semantic-hash/success/prelude/List/concat")
class HashingPreludeListFilterSuite extends HashingSuite("semantic-hash/success/prelude/List/filter")
class HashingPreludeListGenerateSuite extends HashingSuite("semantic-hash/success/prelude/List/generate")
class HashingPreludeListIndexedSuite extends HashingSuite("semantic-hash/success/prelude/List/indexed")
class HashingPreludeListLastSuite extends HashingSuite("semantic-hash/success/prelude/List/last")
class HashingPreludeListMapSuite extends HashingSuite("semantic-hash/success/prelude/List/map")
class HashingPreludeListReplicateSuite extends HashingSuite("semantic-hash/success/prelude/List/replicate")
class HashingPreludeListShiftedSuite extends HashingSuite("semantic-hash/success/prelude/List/shifted")

class HashingPreludeNaturalBuildSuite extends HashingSuite("semantic-hash/success/prelude/Natural/build")
class HashingPreludeNaturalEnumerateSuite extends HashingSuite("semantic-hash/success/prelude/Natural/enumerate")
class HashingPreludeNaturalEvenSuite extends HashingSuite("semantic-hash/success/prelude/Natural/even")
class HashingPreludeNaturalFoldSuite extends HashingSuite("semantic-hash/success/prelude/Natural/fold")
class HashingPreludeNaturalIsZeroSuite extends HashingSuite("semantic-hash/success/prelude/Natural/isZero")
class HashingPreludeNaturalOddSuite extends HashingSuite("semantic-hash/success/prelude/Natural/odd")
class HashingPreludeNaturalProductSuite extends HashingSuite("semantic-hash/success/prelude/Natural/product")
class HashingPreludeNaturalShowSuite extends HashingSuite("semantic-hash/success/prelude/Natural/show")
class HashingPreludeNaturalSumSuite extends HashingSuite("semantic-hash/success/prelude/Natural/sum")
class HashingPreludeNaturalToDoubleSuite extends HashingSuite("semantic-hash/success/prelude/Natural/toDouble")
class HashingPreludeNaturalToIntegerSuite extends HashingSuite("semantic-hash/success/prelude/Natural/toInteger")

class HashingPreludeOptionalAllSuite extends HashingSuite("semantic-hash/success/prelude/Optional/all")
class HashingPreludeOptionalAnySuite extends HashingSuite("semantic-hash/success/prelude/Optional/any")
class HashingPreludeOptionalBuildSuite extends HashingSuite("semantic-hash/success/prelude/Optional/build")
class HashingPreludeOptionalConcatSuite extends HashingSuite("semantic-hash/success/prelude/Optional/concat")
class HashingPreludeOptionalFilterSuite extends HashingSuite("semantic-hash/success/prelude/Optional/filter")
class HashingPreludeOptionalFoldSuite extends HashingSuite("semantic-hash/success/prelude/Optional/fold")
class HashingPreludeOptionalHeadSuite extends HashingSuite("semantic-hash/success/prelude/Optional/head")
class HashingPreludeOptionalLastSuite extends HashingSuite("semantic-hash/success/prelude/Optional/last")
class HashingPreludeOptionalLengthSuite extends HashingSuite("semantic-hash/success/prelude/Optional/length")
class HashingPreludeOptionalMapSuite extends HashingSuite("semantic-hash/success/prelude/Optional/map")
class HashingPreludeOptionalNullSuite extends HashingSuite("semantic-hash/success/prelude/Optional/null")
class HashingPreludeOptionalToListSuite extends HashingSuite("semantic-hash/success/prelude/Optional/toList")
class HashingPreludeOptionalUnzipSuite extends HashingSuite("semantic-hash/success/prelude/Optional/unzip")

class HashingPreludeTextConcatSuite extends HashingSuite("semantic-hash/success/prelude/Text/concat")
class HashingPreludeTextConcatMapSuite extends HashingSuite("semantic-hash/success/prelude/Text/concatMap")
class HashingPreludeTextConcatMapSepSuite extends HashingSuite("semantic-hash/success/prelude/Text/concatMapSep")
class HashingPreludeTextConcatSepSuite extends HashingSuite("semantic-hash/success/prelude/Text/concatSep")
class HashingPreludeTextShowSuite extends HashingSuite("semantic-hash/success/prelude/Text/show")
