package org.dhallj.tests.acceptance

class TypeCheckingBoolAndSuite extends TypeCheckingSuite("type-inference/success/prelude/Bool/and")
class TypeCheckingBoolBuildSuite extends TypeCheckingSuite("type-inference/success/prelude/Bool/build")
class TypeCheckingBoolEvenSuite extends TypeCheckingSuite("type-inference/success/prelude/Bool/even")
class TypeCheckingBoolFoldSuite extends TypeCheckingSuite("type-inference/success/prelude/Bool/fold")
class TypeCheckingBoolNotSuite extends TypeCheckingSuite("type-inference/success/prelude/Bool/not")
class TypeCheckingBoolOddSuite extends TypeCheckingSuite("type-inference/success/prelude/Bool/odd")
class TypeCheckingBoolOrSuite extends TypeCheckingSuite("type-inference/success/prelude/Bool/or")
class TypeCheckingBoolShowSuite extends TypeCheckingSuite("type-inference/success/prelude/Bool/show")

class TypeCheckingDoubleShowSuite extends TypeCheckingSuite("type-inference/success/prelude/Double/show")
class TypeCheckingIntegerShowSuite extends TypeCheckingSuite("type-inference/success/prelude/Integer/show")
class TypeCheckingIntegerToDoubleSuite extends TypeCheckingSuite("type-inference/success/prelude/Integer/toDouble")

class TypeCheckingListAllSuite extends TypeCheckingSuite("type-inference/success/prelude/List/all")
class TypeCheckingListBuildSuite extends TypeCheckingSuite("type-inference/success/prelude/List/build")
class TypeCheckingListConcatMapSuite extends TypeCheckingSuite("type-inference/success/prelude/List/concatMap")
class TypeCheckingListFoldSuite extends TypeCheckingSuite("type-inference/success/prelude/List/fold")
class TypeCheckingListHeadSuite extends TypeCheckingSuite("type-inference/success/prelude/List/head")
class TypeCheckingListIterateSuite extends TypeCheckingSuite("type-inference/success/prelude/List/iterate")
class TypeCheckingListLengthSuite extends TypeCheckingSuite("type-inference/success/prelude/List/length")
class TypeCheckingListNullSuite extends TypeCheckingSuite("type-inference/success/prelude/List/null")
class TypeCheckingListReverseSuite extends TypeCheckingSuite("type-inference/success/prelude/List/reverse")
class TypeCheckingListUnzipSuite extends TypeCheckingSuite("type-inference/success/prelude/List/unzip")
class TypeCheckingListAnySuite extends TypeCheckingSuite("type-inference/success/prelude/List/any")
class TypeCheckingListConcatSuite extends TypeCheckingSuite("type-inference/success/prelude/List/concat")
class TypeCheckingListFilterSuite extends TypeCheckingSuite("type-inference/success/prelude/List/filter")
class TypeCheckingListGenerateSuite extends TypeCheckingSuite("type-inference/success/prelude/List/generate")
class TypeCheckingListIndexedSuite extends TypeCheckingSuite("type-inference/success/prelude/List/indexed")
class TypeCheckingListLastSuite extends TypeCheckingSuite("type-inference/success/prelude/List/last")
class TypeCheckingListMapSuite extends TypeCheckingSuite("type-inference/success/prelude/List/map")
class TypeCheckingListReplicateSuite extends TypeCheckingSuite("type-inference/success/prelude/List/replicate")
class TypeCheckingListShiftedSuite extends TypeCheckingSuite("type-inference/success/prelude/List/shifted")

class TypeCheckingMonoidSuite extends TypeCheckingSuite("type-inference/success/prelude/Monoid")

class TypeCheckingNaturalBuildSuite extends TypeCheckingSuite("type-inference/success/prelude/Natural/build")
class TypeCheckingNaturalEnumerateSuite extends TypeCheckingSuite("type-inference/success/prelude/Natural/enumerate")
class TypeCheckingNaturalEvenSuite extends TypeCheckingSuite("type-inference/success/prelude/Natural/even")
class TypeCheckingNaturalFoldSuite extends TypeCheckingSuite("type-inference/success/prelude/Natural/fold")
class TypeCheckingNaturalIsZeroSuite extends TypeCheckingSuite("type-inference/success/prelude/Natural/isZero")
class TypeCheckingNaturalOddSuite extends TypeCheckingSuite("type-inference/success/prelude/Natural/odd")
class TypeCheckingNaturalProductSuite extends TypeCheckingSuite("type-inference/success/prelude/Natural/product")
class TypeCheckingNaturalShowSuite extends TypeCheckingSuite("type-inference/success/prelude/Natural/show")
class TypeCheckingNaturalSumSuite extends TypeCheckingSuite("type-inference/success/prelude/Natural/sum")
class TypeCheckingNaturalToDoubleSuite extends TypeCheckingSuite("type-inference/success/prelude/Natural/toDouble")
class TypeCheckingNaturalToIntegerSuite extends TypeCheckingSuite("type-inference/success/prelude/Natural/toInteger")

class TypeCheckingOptionalAllSuite extends TypeCheckingSuite("type-inference/success/prelude/Optional/all")
class TypeCheckingOptionalAnySuite extends TypeCheckingSuite("type-inference/success/prelude/Optional/any")
class TypeCheckingOptionalBuildSuite extends TypeCheckingSuite("type-inference/success/prelude/Optional/build")
class TypeCheckingOptionalConcatSuite extends TypeCheckingSuite("type-inference/success/prelude/Optional/concat")
class TypeCheckingOptionalFilterSuite extends TypeCheckingSuite("type-inference/success/prelude/Optional/filter")
class TypeCheckingOptionalFoldSuite extends TypeCheckingSuite("type-inference/success/prelude/Optional/fold")
class TypeCheckingOptionalHeadSuite extends TypeCheckingSuite("type-inference/success/prelude/Optional/head")
class TypeCheckingOptionalLastSuite extends TypeCheckingSuite("type-inference/success/prelude/Optional/last")
class TypeCheckingOptionalLengthSuite extends TypeCheckingSuite("type-inference/success/prelude/Optional/length")
class TypeCheckingOptionalMapSuite extends TypeCheckingSuite("type-inference/success/prelude/Optional/map")
class TypeCheckingOptionalNullSuite extends TypeCheckingSuite("type-inference/success/prelude/Optional/null")
class TypeCheckingOptionalToListSuite extends TypeCheckingSuite("type-inference/success/prelude/Optional/toList")
class TypeCheckingOptionalUnzipSuite extends TypeCheckingSuite("type-inference/success/prelude/Optional/unzip")

class TypeCheckingTextConcatSuite extends TypeCheckingSuite("type-inference/success/prelude/Text/concat")
class TypeCheckingTextConcatMapSuite extends TypeCheckingSuite("type-inference/success/prelude/Text/concatMap")
class TypeCheckingTextConcatMapSepSuite extends TypeCheckingSuite("type-inference/success/prelude/Text/concatMapSep")
class TypeCheckingTextConcatSepSuite extends TypeCheckingSuite("type-inference/success/prelude/Text/concatSep")
