package org.dhallj.tests.acceptance

class TypeCheckingPreludeBoolAndSuite extends PreludeTypeCheckingSuite("type-inference/success/prelude/Bool/and")
class TypeCheckingPreludeBoolBuildSuite extends PreludeTypeCheckingSuite("type-inference/success/prelude/Bool/build")
class TypeCheckingPreludeBoolEvenSuite extends PreludeTypeCheckingSuite("type-inference/success/prelude/Bool/even")
class TypeCheckingPreludeBoolFoldSuite extends PreludeTypeCheckingSuite("type-inference/success/prelude/Bool/fold")
class TypeCheckingPreludeBoolNotSuite extends PreludeTypeCheckingSuite("type-inference/success/prelude/Bool/not")
class TypeCheckingPreludeBoolOddSuite extends PreludeTypeCheckingSuite("type-inference/success/prelude/Bool/odd")
class TypeCheckingPreludeBoolOrSuite extends PreludeTypeCheckingSuite("type-inference/success/prelude/Bool/or")
class TypeCheckingPreludeBoolShowSuite extends PreludeTypeCheckingSuite("type-inference/success/prelude/Bool/show")

class TypeCheckingPreludeDoubleShowSuite extends PreludeTypeCheckingSuite("type-inference/success/prelude/Double/show")
class TypeCheckingPreludeIntegerShowSuite extends PreludeTypeCheckingSuite("type-inference/success/prelude/Integer/show")
class TypeCheckingPreludeIntegerToDoubleSuite
    extends PreludeTypeCheckingSuite("type-inference/success/prelude/Integer/toDouble")

class TypeCheckingPreludeListAllSuite extends PreludeTypeCheckingSuite("type-inference/success/prelude/List/all")
class TypeCheckingPreludeListBuildSuite extends PreludeTypeCheckingSuite("type-inference/success/prelude/List/build")
class TypeCheckingPreludeListConcatMapSuite extends PreludeTypeCheckingSuite("type-inference/success/prelude/List/concatMap")
class TypeCheckingPreludeListFoldSuite extends PreludeTypeCheckingSuite("type-inference/success/prelude/List/fold")
class TypeCheckingPreludeListHeadSuite extends PreludeTypeCheckingSuite("type-inference/success/prelude/List/head")
class TypeCheckingPreludeListIterateSuite extends PreludeTypeCheckingSuite("type-inference/success/prelude/List/iterate")
class TypeCheckingPreludeListLengthSuite extends PreludeTypeCheckingSuite("type-inference/success/prelude/List/length")
class TypeCheckingPreludeListNullSuite extends PreludeTypeCheckingSuite("type-inference/success/prelude/List/null")
class TypeCheckingPreludeListReverseSuite extends PreludeTypeCheckingSuite("type-inference/success/prelude/List/reverse")
class TypeCheckingPreludeListUnzipSuite extends PreludeTypeCheckingSuite("type-inference/success/prelude/List/unzip")
class TypeCheckingPreludeListAnySuite extends PreludeTypeCheckingSuite("type-inference/success/prelude/List/any")
class TypeCheckingPreludeListConcatSuite extends PreludeTypeCheckingSuite("type-inference/success/prelude/List/concat")
class TypeCheckingPreludeListFilterSuite extends PreludeTypeCheckingSuite("type-inference/success/prelude/List/filter")
class TypeCheckingPreludeListGenerateSuite extends PreludeTypeCheckingSuite("type-inference/success/prelude/List/generate")
class TypeCheckingPreludeListIndexedSuite extends PreludeTypeCheckingSuite("type-inference/success/prelude/List/indexed")
class TypeCheckingPreludeListLastSuite extends PreludeTypeCheckingSuite("type-inference/success/prelude/List/last")
class TypeCheckingPreludeListMapSuite extends PreludeTypeCheckingSuite("type-inference/success/prelude/List/map")
class TypeCheckingPreludeListReplicateSuite extends PreludeTypeCheckingSuite("type-inference/success/prelude/List/replicate")
class TypeCheckingPreludeListShiftedSuite extends PreludeTypeCheckingSuite("type-inference/success/prelude/List/shifted")

class TypeCheckingPreludeMonoidSuite extends PreludeTypeCheckingSuite("type-inference/success/prelude/Monoid")

class TypeCheckingPreludeNaturalBuildSuite extends PreludeTypeCheckingSuite("type-inference/success/prelude/Natural/build")
class TypeCheckingPreludeNaturalEnumerateSuite
    extends PreludeTypeCheckingSuite("type-inference/success/prelude/Natural/enumerate")
class TypeCheckingPreludeNaturalEvenSuite extends PreludeTypeCheckingSuite("type-inference/success/prelude/Natural/even")
class TypeCheckingPreludeNaturalFoldSuite extends PreludeTypeCheckingSuite("type-inference/success/prelude/Natural/fold")
class TypeCheckingPreludeNaturalIsZeroSuite extends PreludeTypeCheckingSuite("type-inference/success/prelude/Natural/isZero")
class TypeCheckingPreludeNaturalOddSuite extends PreludeTypeCheckingSuite("type-inference/success/prelude/Natural/odd")
class TypeCheckingPreludeNaturalProductSuite extends PreludeTypeCheckingSuite("type-inference/success/prelude/Natural/product")
class TypeCheckingPreludeNaturalShowSuite extends PreludeTypeCheckingSuite("type-inference/success/prelude/Natural/show")
class TypeCheckingPreludeNaturalSumSuite extends PreludeTypeCheckingSuite("type-inference/success/prelude/Natural/sum")
class TypeCheckingPreludeNaturalToDoubleSuite
    extends PreludeTypeCheckingSuite("type-inference/success/prelude/Natural/toDouble")
class TypeCheckingPreludeNaturalToIntegerSuite
    extends PreludeTypeCheckingSuite("type-inference/success/prelude/Natural/toInteger")

class TypeCheckingPreludeOptionalAllSuite extends PreludeTypeCheckingSuite("type-inference/success/prelude/Optional/all")
class TypeCheckingPreludeOptionalAnySuite extends PreludeTypeCheckingSuite("type-inference/success/prelude/Optional/any")
class TypeCheckingPreludeOptionalBuildSuite extends PreludeTypeCheckingSuite("type-inference/success/prelude/Optional/build")
class TypeCheckingPreludeOptionalConcatSuite extends PreludeTypeCheckingSuite("type-inference/success/prelude/Optional/concat")
class TypeCheckingPreludeOptionalFilterSuite extends PreludeTypeCheckingSuite("type-inference/success/prelude/Optional/filter")
class TypeCheckingPreludeOptionalFoldSuite extends PreludeTypeCheckingSuite("type-inference/success/prelude/Optional/fold")
class TypeCheckingPreludeOptionalHeadSuite extends PreludeTypeCheckingSuite("type-inference/success/prelude/Optional/head")
class TypeCheckingPreludeOptionalLastSuite extends PreludeTypeCheckingSuite("type-inference/success/prelude/Optional/last")
class TypeCheckingPreludeOptionalLengthSuite extends PreludeTypeCheckingSuite("type-inference/success/prelude/Optional/length")
class TypeCheckingPreludeOptionalMapSuite extends PreludeTypeCheckingSuite("type-inference/success/prelude/Optional/map")
class TypeCheckingPreludeOptionalNullSuite extends PreludeTypeCheckingSuite("type-inference/success/prelude/Optional/null")
class TypeCheckingPreludeOptionalToListSuite extends PreludeTypeCheckingSuite("type-inference/success/prelude/Optional/toList")
class TypeCheckingPreludeOptionalUnzipSuite extends PreludeTypeCheckingSuite("type-inference/success/prelude/Optional/unzip")

class TypeCheckingPreludeTextConcatSuite extends PreludeTypeCheckingSuite("type-inference/success/prelude/Text/concat")
class TypeCheckingPreludeTextConcatMapSuite extends PreludeTypeCheckingSuite("type-inference/success/prelude/Text/concatMap")
class TypeCheckingPreludeTextConcatMapSepSuite
    extends PreludeTypeCheckingSuite("type-inference/success/prelude/Text/concatMapSep")
class TypeCheckingPreludeTextConcatSepSuite extends PreludeTypeCheckingSuite("type-inference/success/prelude/Text/concatSep")
