package org.dhallj.tests

class TypeCheckingPreludeBoolAndSuite extends TypeCheckingSuite("type-inference/success/prelude/Bool/and")
class TypeCheckingPreludeBoolBuildSuite extends TypeCheckingSuite("type-inference/success/prelude/Bool/build")
class TypeCheckingPreludeBoolEvenSuite extends TypeCheckingSuite("type-inference/success/prelude/Bool/even")
class TypeCheckingPreludeBoolFoldSuite extends TypeCheckingSuite("type-inference/success/prelude/Bool/fold")
class TypeCheckingPreludeBoolNotSuite extends TypeCheckingSuite("type-inference/success/prelude/Bool/not")
class TypeCheckingPreludeBoolOddSuite extends TypeCheckingSuite("type-inference/success/prelude/Bool/odd")
class TypeCheckingPreludeBoolOrSuite extends TypeCheckingSuite("type-inference/success/prelude/Bool/or")
class TypeCheckingPreludeBoolShowSuite extends TypeCheckingSuite("type-inference/success/prelude/Bool/show")

class TypeCheckingPreludeDoubleShowSuite extends TypeCheckingSuite("type-inference/success/prelude/Double/show")
class TypeCheckingPreludeIntegerShowSuite extends TypeCheckingSuite("type-inference/success/prelude/Integer/show")
class TypeCheckingPreludeIntegerToDoubleSuite
    extends TypeCheckingSuite("type-inference/success/prelude/Integer/toDouble")

class TypeCheckingPreludeListAllSuite extends TypeCheckingSuite("type-inference/success/prelude/List/all")
class TypeCheckingPreludeListBuildSuite extends TypeCheckingSuite("type-inference/success/prelude/List/build")
class TypeCheckingPreludeListConcatMapSuite extends TypeCheckingSuite("type-inference/success/prelude/List/concatMap")
class TypeCheckingPreludeListFoldSuite extends TypeCheckingSuite("type-inference/success/prelude/List/fold")
class TypeCheckingPreludeListHeadSuite extends TypeCheckingSuite("type-inference/success/prelude/List/head")
class TypeCheckingPreludeListIterateSuite extends TypeCheckingSuite("type-inference/success/prelude/List/iterate")
class TypeCheckingPreludeListLengthSuite extends TypeCheckingSuite("type-inference/success/prelude/List/length")
class TypeCheckingPreludeListNullSuite extends TypeCheckingSuite("type-inference/success/prelude/List/null")
class TypeCheckingPreludeListReverseSuite extends TypeCheckingSuite("type-inference/success/prelude/List/reverse")
class TypeCheckingPreludeListUnzipSuite extends TypeCheckingSuite("type-inference/success/prelude/List/unzip")
class TypeCheckingPreludeListAnySuite extends TypeCheckingSuite("type-inference/success/prelude/List/any")
class TypeCheckingPreludeListConcatSuite extends TypeCheckingSuite("type-inference/success/prelude/List/concat")
class TypeCheckingPreludeListFilterSuite extends TypeCheckingSuite("type-inference/success/prelude/List/filter")
class TypeCheckingPreludeListGenerateSuite extends TypeCheckingSuite("type-inference/success/prelude/List/generate")
class TypeCheckingPreludeListIndexedSuite extends TypeCheckingSuite("type-inference/success/prelude/List/indexed")
class TypeCheckingPreludeListLastSuite extends TypeCheckingSuite("type-inference/success/prelude/List/last")
class TypeCheckingPreludeListMapSuite extends TypeCheckingSuite("type-inference/success/prelude/List/map")
class TypeCheckingPreludeListReplicateSuite extends TypeCheckingSuite("type-inference/success/prelude/List/replicate")
class TypeCheckingPreludeListShiftedSuite extends TypeCheckingSuite("type-inference/success/prelude/List/shifted")

class TypeCheckingPreludeMonoidSuite extends TypeCheckingSuite("type-inference/success/prelude/Monoid")

class TypeCheckingPreludeNaturalBuildSuite extends TypeCheckingSuite("type-inference/success/prelude/Natural/build")
class TypeCheckingPreludeNaturalEnumerateSuite
    extends TypeCheckingSuite("type-inference/success/prelude/Natural/enumerate")
class TypeCheckingPreludeNaturalEvenSuite extends TypeCheckingSuite("type-inference/success/prelude/Natural/even")
class TypeCheckingPreludeNaturalFoldSuite extends TypeCheckingSuite("type-inference/success/prelude/Natural/fold")
class TypeCheckingPreludeNaturalIsZeroSuite extends TypeCheckingSuite("type-inference/success/prelude/Natural/isZero")
class TypeCheckingPreludeNaturalOddSuite extends TypeCheckingSuite("type-inference/success/prelude/Natural/odd")
class TypeCheckingPreludeNaturalProductSuite extends TypeCheckingSuite("type-inference/success/prelude/Natural/product")
class TypeCheckingPreludeNaturalShowSuite extends TypeCheckingSuite("type-inference/success/prelude/Natural/show")
class TypeCheckingPreludeNaturalSumSuite extends TypeCheckingSuite("type-inference/success/prelude/Natural/sum")
class TypeCheckingPreludeNaturalToDoubleSuite
    extends TypeCheckingSuite("type-inference/success/prelude/Natural/toDouble")
class TypeCheckingPreludeNaturalToIntegerSuite
    extends TypeCheckingSuite("type-inference/success/prelude/Natural/toInteger")

class TypeCheckingPreludeOptionalAllSuite extends TypeCheckingSuite("type-inference/success/prelude/Optional/all")
class TypeCheckingPreludeOptionalAnySuite extends TypeCheckingSuite("type-inference/success/prelude/Optional/any")
class TypeCheckingPreludeOptionalBuildSuite extends TypeCheckingSuite("type-inference/success/prelude/Optional/build")
class TypeCheckingPreludeOptionalConcatSuite extends TypeCheckingSuite("type-inference/success/prelude/Optional/concat")
class TypeCheckingPreludeOptionalFilterSuite extends TypeCheckingSuite("type-inference/success/prelude/Optional/filter")
class TypeCheckingPreludeOptionalFoldSuite extends TypeCheckingSuite("type-inference/success/prelude/Optional/fold")
class TypeCheckingPreludeOptionalHeadSuite extends TypeCheckingSuite("type-inference/success/prelude/Optional/head")
class TypeCheckingPreludeOptionalLastSuite extends TypeCheckingSuite("type-inference/success/prelude/Optional/last")
class TypeCheckingPreludeOptionalLengthSuite extends TypeCheckingSuite("type-inference/success/prelude/Optional/length")
class TypeCheckingPreludeOptionalMapSuite extends TypeCheckingSuite("type-inference/success/prelude/Optional/map")
class TypeCheckingPreludeOptionalNullSuite extends TypeCheckingSuite("type-inference/success/prelude/Optional/null")
class TypeCheckingPreludeOptionalToListSuite extends TypeCheckingSuite("type-inference/success/prelude/Optional/toList")
class TypeCheckingPreludeOptionalUnzipSuite extends TypeCheckingSuite("type-inference/success/prelude/Optional/unzip")

class TypeCheckingPreludeTextConcatSuite extends TypeCheckingSuite("type-inference/success/prelude/Text/concat")
class TypeCheckingPreludeTextConcatMapSuite extends TypeCheckingSuite("type-inference/success/prelude/Text/concatMap")
class TypeCheckingPreludeTextConcatMapSepSuite
    extends TypeCheckingSuite("type-inference/success/prelude/Text/concatMapSep")
class TypeCheckingPreludeTextConcatSepSuite extends TypeCheckingSuite("type-inference/success/prelude/Text/concatSep")
